In [54]:
import pandas as pd

In [55]:
import pandas as pd

In [56]:
df=pd.read_csv('SalaryData.csv')

In [57]:
df

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
...,...,...,...,...,...,...
370,35.0,Female,Bachelor's,Senior Marketing Analyst,8.0,85000.0
371,43.0,Male,Master's,Director of Operations,19.0,170000.0
372,29.0,Female,Bachelor's,Junior Project Manager,2.0,40000.0
373,34.0,Male,Bachelor's,Senior Operations Coordinator,7.0,90000.0
374,44.0,Female,PhD,Senior Business Analyst,15.0,150000.0

In [58]:
df.head()

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0

In [59]:
df.tail()

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
370,35.0,Female,Bachelor's,Senior Marketing Analyst,8.0,85000.0
371,43.0,Male,Master's,Director of Operations,19.0,170000.0
372,29.0,Female,Bachelor's,Junior Project Manager,2.0,40000.0
373,34.0,Male,Bachelor's,Senior Operations Coordinator,7.0,90000.0
374,44.0,Female,PhD,Senior Business Analyst,15.0,150000.0

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375 entries, 0 to 374
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  373 non-null    float64
 1   Gender               373 non-null    object
 2   Education Level      373 non-null    object
 3   Job Title            373 non-null    object
 4   Years of Experience  373 non-null    float64
 5   Salary               373 non-null    float64
dtypes: float64(3), object(3)
memory usage: 17.7+ KB

In [61]:
df.describe()

              Age  Years of Experience         Salary
count  373.000000           373.000000     373.000000
mean    37.431635            10.030831  100577.345845
std      7.069073             6.557007   48240.013482
min     23.000000             0.000000     350.000000
25%     31.000000             4.000000   55000.000000
50%     36.000000             9.000000   95000.000000
75%     44.000000            15.000000  140000.000000
max     53.000000            25.000000  250000.000000

In [62]:
df.isnull().sum()

Age                    2
Gender                 2
Education Level        2
Job Title              2
Years of Experience    2
Salary                 2
dtype: int64

In [63]:
df.columns

Index(['Age', 'Gender', 'Education Level', 'Job Title', 'Years of Experience',
       'Salary'],
      dtype='object')

In [64]:
df=df.dropna(subset=['Age', 'Gender', 'Education Level', 'Job Title', 'Years of Experience',
       'Salary'])

In [65]:
df.isnull().sum()

Age                    0
Gender                 0
Education Level        0
Job Title              0
Years of Experience    0
Salary                 0
dtype: int64

In [66]:
df

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
...,...,...,...,...,...,...
370,35.0,Female,Bachelor's,Senior Marketing Analyst,8.0,85000.0
371,43.0,Male,Master's,Director of Operations,19.0,170000.0
372,29.0,Female,Bachelor's,Junior Project Manager,2.0,40000.0
373,34.0,Male,Bachelor's,Senior Operations Coordinator,7.0,90000.0
374,44.0,Female,PhD,Senior Business Analyst,15.0,150000.0

In [67]:
df["Age"]=df["Age"].astype(int)

C:\Users\saraj\AppData\Local\Temp\ipykernel_6940\2332842721.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"]=df["Age"].astype(int)

In [68]:
df

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28,Female,Master's,Data Analyst,3.0,65000.0
2,45,Male,PhD,Senior Manager,15.0,150000.0
3,36,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52,Male,Master's,Director,20.0,200000.0
...,...,...,...,...,...,...
370,35,Female,Bachelor's,Senior Marketing Analyst,8.0,85000.0
371,43,Male,Master's,Director of Operations,19.0,170000.0
372,29,Female,Bachelor's,Junior Project Manager,2.0,40000.0
373,34,Male,Bachelor's,Senior Operations Coordinator,7.0,90000.0
374,44,Female,PhD,Senior Business Analyst,15.0,150000.0

In [69]:
def gender(g):
    if g=="Male":
       return 0
    elif g=="Female":
        return 1

df["Gender"]=df["Gender"].apply(gender)

C:\Users\saraj\AppData\Local\Temp\ipykernel_6940\743046188.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Gender"]=df["Gender"].apply(gender)

In [70]:
df

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32,0,Bachelor's,Software Engineer,5.0,90000.0
1,28,1,Master's,Data Analyst,3.0,65000.0
2,45,0,PhD,Senior Manager,15.0,150000.0
3,36,1,Bachelor's,Sales Associate,7.0,60000.0
4,52,0,Master's,Director,20.0,200000.0
...,...,...,...,...,...,...
370,35,1,Bachelor's,Senior Marketing Analyst,8.0,85000.0
371,43,0,Master's,Director of Operations,19.0,170000.0
372,29,1,Bachelor's,Junior Project Manager,2.0,40000.0
373,34,0,Bachelor's,Senior Operations Coordinator,7.0,90000.0
374,44,1,PhD,Senior Business Analyst,15.0,150000.0

In [71]:
df["Education Level"].value_counts()

Education Level
Bachelor's    224
Master's       98
PhD            51
Name: count, dtype: int64

In [72]:
def edu(e):
    if e=="Bachelor's":
        return 0 
    elif e=="Master's":
        return 1
    elif e=="PhD":
        return 2

df["Education Level"]=df["Education Level"].apply(edu)

C:\Users\saraj\AppData\Local\Temp\ipykernel_6940\889812437.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Education Level"]=df["Education Level"].apply(edu)

In [73]:
df

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32,0,0,Software Engineer,5.0,90000.0
1,28,1,1,Data Analyst,3.0,65000.0
2,45,0,2,Senior Manager,15.0,150000.0
3,36,1,0,Sales Associate,7.0,60000.0
4,52,0,1,Director,20.0,200000.0
...,...,...,...,...,...,...
370,35,1,0,Senior Marketing Analyst,8.0,85000.0
371,43,0,1,Director of Operations,19.0,170000.0
372,29,1,0,Junior Project Manager,2.0,40000.0
373,34,0,0,Senior Operations Coordinator,7.0,90000.0
374,44,1,2,Senior Business Analyst,15.0,150000.0

In [74]:
df["Years of Experience"]=df["Years of Experience"].astype(int)
df["Salary"]=df["Salary"].astype(int)

C:\Users\saraj\AppData\Local\Temp\ipykernel_6940\4059112407.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Years of Experience"]=df["Years of Experience"].astype(int)
C:\Users\saraj\AppData\Local\Temp\ipykernel_6940\4059112407.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Salary"]=df["Salary"].astype(int)

In [75]:
df

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32,0,0,Software Engineer,5,90000
1,28,1,1,Data Analyst,3,65000
2,45,0,2,Senior Manager,15,150000
3,36,1,0,Sales Associate,7,60000
4,52,0,1,Director,20,200000
...,...,...,...,...,...,...
370,35,1,0,Senior Marketing Analyst,8,85000
371,43,0,1,Director of Operations,19,170000
372,29,1,0,Junior Project Manager,2,40000
373,34,0,0,Senior Operations Coordinator,7,90000
374,44,1,2,Senior Business Analyst,15,150000